services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin123
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed/postgres_seed.sql:/docker-entrypoint-initdb.d/01_seed.sql
      - ./seed/postgres_config.sql:/docker-entrypoint-initdb.d/00_config.sql
    command: >
      postgres
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.track=all
        -c log_min_duration_statement=500
        -c track_activities=on
        -c track_counts=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbadmin -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: dbadmin123
      MONGO_INITDB_DATABASE: appdb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./seed/mongo_seed.js:/docker-entrypoint-initdb.d/seed.js
    command: ["mongod", "--profile", "2", "--slowms", "100"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "dbadmin", "-p", "dbadmin123"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  mongodata:
